name: Build Docker Image

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
env:
  SYSDIG_URL: https://app.au1.sysdig.com
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BYPASS_SCAN_FAIL: false

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Download go Dependencies
      run: |
        go get google.golang.org/grpc
        go get rsc.io/quote
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }} --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Sysdig Secure Inline Scan
      uses: sysdiglabs/scan-action@v5
      with:
        image-tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
        sysdig-secure-url: ${{ env.SYSDIG_URL }}
        sysdig-secure-token: ${{ secrets.SECURE_API_TOKEN }}
        stop-on-failed-policy-eval: ${{ env.BYPASS_SCAN_FAIL }}

    - name: Log in to the Container registry
      run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
    
    - name: Push the Docker image
      run: docker push -a ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
